name: slugify
version: 1.0.0
description: >-
  Converts a string into a slug.
  Useful for URLs, filenames, IDs, and more.
author: izolate <yoshtalwar@gmail.com>
homepage: https://github.com/izolate/slugify
documentation: https://github.com/izolate/slugify/blob/master/README.md
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.16.4
